// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-nw8JFu19I3v55Z77WQGHHIlkLUwhs8s',
    appId: '1:380664274278:web:552da524563c37c0693ca7',
    messagingSenderId: '380664274278',
    projectId: 'reddit-news-a7692',
    authDomain: 'reddit-news-a7692.firebaseapp.com',
    storageBucket: 'reddit-news-a7692.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsu0MVzPrytsR_3irRmqMmbEYQcN794uM',
    appId: '1:380664274278:android:d79aeb5d48edad8d693ca7',
    messagingSenderId: '380664274278',
    projectId: 'reddit-news-a7692',
    storageBucket: 'reddit-news-a7692.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9MnZ0ULwgF1SmsQYxbZS3TZoyIl3-Q-8',
    appId: '1:380664274278:ios:dbad4cf1301891c0693ca7',
    messagingSenderId: '380664274278',
    projectId: 'reddit-news-a7692',
    storageBucket: 'reddit-news-a7692.appspot.com',
    iosBundleId: 'com.example.redditNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9MnZ0ULwgF1SmsQYxbZS3TZoyIl3-Q-8',
    appId: '1:380664274278:ios:810b010543444765693ca7',
    messagingSenderId: '380664274278',
    projectId: 'reddit-news-a7692',
    storageBucket: 'reddit-news-a7692.appspot.com',
    iosBundleId: 'com.example.redditNew.RunnerTests',
  );
}
